const serviceProviders = [
  {
    id: "mu-chen",
    name: "暮辰妆造",
    role: "makeup",
    roleLabel: "妆娘",
    city: "北京",
    district: "朝阳",
    price: 260,
    rating: 4.8,
    availableDates: ["2026-07-16", "2026-07-18", "2026-07-20"],
    styles: ["电影感", "冷色调", "崩铁", "精致妆面"],
    portfolio: "银狼 / 镜流 / 芙宁娜",
    note: "擅长冷白皮、眼妆结构和角色还原。",
    accent: "#6d8cff",
  },
  {
    id: "nanako",
    name: "Nanako 妆造",
    role: "makeup",
    roleLabel: "妆娘",
    city: "北京",
    district: "海淀",
    price: 180,
    rating: 4.5,
    availableDates: ["2026-07-17", "2026-07-18"],
    styles: ["甜系", "日常感", "动漫"],
    portfolio: "初音 / 喜多川海梦 / 星野爱",
    note: "价格友好，适合轻量棚拍和漫展妆。",
    accent: "#f476a1",
  },
  {
    id: "zero-lens",
    name: "Zero Lens",
    role: "photographer",
    roleLabel: "摄影师",
    city: "北京",
    district: "东城",
    price: 360,
    rating: 4.9,
    availableDates: ["2026-07-18", "2026-07-21"],
    styles: ["电影感", "暗调", "游戏", "棚拍"],
    portfolio: "暗调棚拍 / 赛博布光 / 剧情感人像",
    note: "强灯光控制，适合剧情感、暗调和科幻布景拍摄。",
    accent: "#0f766e",
  },
  {
    id: "light-river",
    name: "Light River",
    role: "photographer",
    roleLabel: "摄影师",
    city: "北京",
    district: "通州",
    price: 260,
    rating: 4.6,
    availableDates: ["2026-07-17", "2026-07-18", "2026-07-19"],
    styles: ["清透", "自然光", "动漫", "外景"],
    portfolio: "自然光外景 / 清透人像 / 漫展跟拍",
    note: "适合清透、自然光、外景和低预算拍摄。",
    accent: "#3b82f6",
  },
  {
    id: "noir-studio",
    name: "Noir Studio",
    role: "studio",
    roleLabel: "摄影棚",
    city: "北京",
    district: "朝阳",
    price: 160,
    rating: 4.7,
    availableDates: ["2026-07-18", "2026-07-19"],
    styles: ["电影感", "暗调", "机械", "棚拍"],
    portfolio: "黑箱棚 / 金属布景 / 可控灯",
    note: "两小时起租，适合科幻与游戏角色。",
    accent: "#475569",
  },
  {
    id: "mori-studio",
    name: "Mori Studio",
    role: "studio",
    roleLabel: "摄影棚",
    city: "北京",
    district: "丰台",
    price: 120,
    rating: 4.4,
    availableDates: ["2026-07-17", "2026-07-18", "2026-07-20"],
    styles: ["清透", "日系", "自然光"],
    portfolio: "白棚 / 木质窗景 / 花墙",
    note: "预算友好，适合明亮风格。",
    accent: "#16a34a",
  },
  {
    id: "wig-lab",
    name: "Wig Lab",
    role: "wig",
    roleLabel: "毛娘/假发",
    city: "北京",
    district: "海淀",
    price: 130,
    rating: 4.6,
    availableDates: ["2026-07-15", "2026-07-16", "2026-07-18"],
    styles: ["游戏", "高还原", "定型"],
    portfolio: "银狼 / 丹恒 / 黑塔",
    note: "可做快速修毛和拍摄前定型。",
    accent: "#a855f7",
  },
  {
    id: "afterglow",
    name: "Afterglow 后期",
    role: "retouch",
    roleLabel: "后期",
    city: "北京",
    district: "远程",
    price: 90,
    rating: 4.5,
    availableDates: ["2026-07-19", "2026-07-20", "2026-07-22"],
    styles: ["电影感", "暗调", "肤色修正"],
    portfolio: "赛博调色 / 氛围合成 / 人像精修",
    note: "远程交付，可作为预算有余时的增强项。",
    accent: "#ea580c",
  },
];

const defaultRequirement = {
  character: "银狼",
  fandom: "崩坏:星穹铁道",
  city: "北京",
  dateStart: "2026-07-16",
  dateEnd: "2026-07-18",
  preferredDate: "2026-07-18",
  budget: 800,
  style: "电影感",
  ownedItems: ["服装"],
  notes: "想拍棚拍正片，偏暗调和游戏感，希望尽量少自己沟通。",
  rawText: "我想在7月16到18日之间，在北京拍《崩坏:星穹铁道》银狼，预算800元以内，偏电影感/暗调，目前只有服装，希望少一点自己沟通。",
};

const roleRequirements = [
  { role: "makeup", label: "妆娘", neededWhenMissing: ["妆造"] },
  { role: "wig", label: "毛娘/假发", neededWhenMissing: ["假发", "发型"] },
  { role: "photographer", label: "摄影师", neededWhenMissing: ["摄影"] },
  { role: "studio", label: "摄影棚", neededWhenMissing: ["场地"] },
  { role: "retouch", label: "后期", optional: true, neededWhenMissing: ["后期"] },
];




window.serviceProviders = serviceProviders;
window.defaultRequirement = defaultRequirement;
window.roleRequirements = roleRequirements;


